FROM oven/bun:1 AS base
WORKDIR /app

# 複製 package.json 和 bun.lock
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# 複製 nuxt 配置檔案
COPY nuxt.config.ts ./

# 設置環境變數
ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 3000

CMD ["bun", "run", "dev"]
