fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    # General
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: destroyed-symlinks
    - id: check-symlinks
    - id: check-added-large-files
    # Syntax
    - id: check-toml
    - id: check-json
      exclude: "tsconfig.json"
    - id: check-yaml
    # python
    - id: check-ast
    - id: debug-statements
    - id: fix-encoding-pragma
      args: [--remove]

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
